apiVersion: v1
kind: Service
metadata:
  	name: brain-tasks-service
spec:
  	type: NodePort
  	selector:
    	app: brain-tasks-app
  	ports:
    	- port: 3000
      	targetPort: 3000
      	nodePort: 30007

